### PR TITLE
Bug 1907375: bump(*): k8s 1.20

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
This lgtm, but you have a bug in the code:
```
# github.com/openshift/cluster-kube-scheduler-operator/pkg/operator/targetconfigcontroller
pkg/operator/targetconfigcontroller/targetconfigcontroller.go:299:8: undefined: "github.com/openshift/api/config/v1".HighNodeUtililzation
# github.com/openshift/cluster-kube-scheduler-operator/pkg/operator/targetconfigcontroller
vet: pkg/operator/targetconfigcontroller/targetconfigcontroller.go:299:11: HighNodeUtililzation not declared by package v1
```

**Review by damemi — COMMENTED** [review]
@soltysh looks like we fixed a typo and I missed it :) updated

**Comment by mfojtik** [comment]
@damemi looks like the unit tests need update (feature gates)

**Comment by soltysh** [comment]
@damemi looks like all this merged yesterday with https://github.com/openshift/cluster-kube-scheduler-operator/pull/313
/close

**Pull request closed without merging**
