### PR TITLE
Bug 1879019: Explicitly use internal LB for KS

### PR DESCRIPTION
**Pull request by tnozicka**
This fixes webhooks and anything else that didn't have the patch for the override. It also makes the intention clearer in the kubeconfig with the actual URL there.

/cc @soltysh @deads2k

### CODE REVIEW

**Comment by tnozicka** [comment]
```
2020/09/16 13:36:27 pod didn't start running within 10 minutes: 
* Container artifacts is not ready with reason PodInitializing and message 
* Container test is not ready with reason PodInitializing and message 
2020/09/16 13:37:04 error: artifacts container for pod e2e-aws-serial-ipi-conf unready: timed out waiting for the condition
2020/09/16 13:37:32 pod didn't start running within 10 minutes: 
```
/retest

**Review by soltysh — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
