### PR TITLE
bug 2005901: Guard controller pdb

### PR DESCRIPTION
**Pull request by ingvagabund**
Running in my cluster (after deploying the scheduler operator with the changes)

```
NAME                                                                  READY   STATUS    RESTARTS   AGE
openshift-kube-scheduler-ip-10-0-144-236.us-east-2.compute.internal   3/3     Running   0          13m
openshift-kube-scheduler-ip-10-0-169-240.us-east-2.compute.internal   3/3     Running   0          15m
openshift-kube-scheduler-ip-10-0-227-47.us-east-2.compute.internal    3/3     Running   0          55s
NAME                                                                        READY   STATUS    RESTARTS   AGE
openshift-kube-scheduler-guard-ip-10-0-144-236.us-east-2.compute.internal   1/1     Running   0          94s
openshift-kube-scheduler-guard-ip-10-0-169-240.us-east-2.compute.internal   1/1     Running   0          91s
openshift-kube-scheduler-guard-ip-10-0-227-47.us-east-2.compute.internal    1/1     Running   0          87s
```

/hold
TBD

Pulling https://github.com/openshift/library-go/pull/1238

### CODE REVIEW

**Comment by ingvagabund** [comment]
Waiting for https://github.com/openshift/library-go/pull/1238

**Comment by ingvagabund** [comment]
Checking https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-scheduler-operator/373/pull-ci-openshift-cluster-kube-scheduler-operator-master-e2e-aws/1471815198951084032/artifacts/e2e-aws/gather-extra/artifacts/pods/:
```
 openshift-kube-scheduler_openshift-kube-scheduler-guard-ip-10-0-154-38.us-west-2.compute.internal_guard.log
 openshift-kube-scheduler_openshift-kube-scheduler-guard-ip-10-0-154-38.us-west-2.compute.internal_guard_previous.log
 openshift-kube-scheduler_openshift-kube-scheduler-guard-ip-10-0-170-57.us-west-2.compute.internal_guard.log
 openshift-kube-scheduler_openshift-kube-scheduler-guard-ip-10-0-170-57.us-west-2.compute.internal_guard_previous.log
 openshift-kube-scheduler_openshift-kube-scheduler-guard-ip-10-0-241-117.us-west-2.compute.internal_guard.log
 openshift-kube-scheduler_openshift-kube-scheduler-guard-ip-10-0-241-117.us-west-2.compute.internal_guard_previous.log
```

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ingvagabund** [comment]
/hold
until https://github.com/openshift/library-go/pull/1268#discussion_r770769105 gets resolved through https://github.com/openshift/library-go/pull/1272

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
