### PR TITLE
Bug 1908145: Change recovery-controller port to avoid conflicts

### PR DESCRIPTION
**Pull request by damemi**
This changes the recovery-controller port to `11443`, to avoid conflicting with the router

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @soltysh @tnozicka 
is this a reasonable port, and are there any other places this needs to be updated? I'm not very familiar with the recovery controller

**Comment by damemi** [comment]
bump
@tnozicka @soltysh does this look good to you?

**Review by tnozicka — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
