### PR TITLE
Bug 1769013: use openshift/api yamls

### PR DESCRIPTION
**Pull request by soltysh**
/assign @damemi

### CODE REVIEW

**Comment by damemi** [comment]
Looks like it's failing on the target config reconciler feature gates unit test?
```
 go test -race ./pkg/... ./cmd/...
?   	github.com/openshift/cluster-kube-scheduler-operator/pkg/cmd/operator	[no test files]
--- FAIL: TestCheckForFeatureGates (0.00s)
    --- FAIL: TestCheckForFeatureGates/default (0.00s)
        target_config_reconciler_v410_00_test.go:56: Expected map[ExperimentalCriticalPodAnnotation:true LocalStorageCapacityIsolation:false RotateKubeletServerCertificate:true SupportPodPidsLimit:true TLSSecurityProfile:true] feature gates to be present but found map[ExperimentalCriticalPodAnnotation:true LegacyNodeRoleBehavior:false NodeDisruptionExclusion:true RotateKubeletServerCertificate:true ServiceNodeExclusion:true SupportPodPidsLimit:true TLSSecurityProfile:true]
    --- FAIL: TestCheckForFeatureGates/techpreview (0.00s)
        target_config_reconciler_v410_00_test.go:56: Expected map[ExperimentalCriticalPodAnnotation:true LocalStorageCapacityIsolation:false RotateKubeletServerCertificate:true SupportPodPidsLimit:true TLSSecurityProfile:true] feature gates to be present but found map[ExperimentalCriticalPodAnnotation:true LegacyNodeRoleBehavior:false NodeDisruptionExclusion:true RotateKubeletServerCertificate:true ServiceNodeExclusion:true SupportPodPidsLimit:true TLSSecurityProfile:true] 
```

**Comment by damemi** [comment]
I think the expected feature gates in [this test](https://github.com/openshift/cluster-kube-scheduler-operator/blob/master/pkg/operator/target_config_reconciler_v410_00_test.go#L20-L38) need to be updated to match [these constants](https://github.com/openshift/api/blob/master/config/v1/types_feature.go#L100-L128)

**Comment by soltysh** [comment]
> I think the expected feature gates in [this test](https://github.com/openshift/cluster-kube-scheduler-operator/blob/master/pkg/operator/target_config_reconciler_v410_00_test.go#L20-L38) need to be updated to match [these constants](https://github.com/openshift/api/blob/master/config/v1/types_feature.go#L100-L128)

Yup, updated. @damemi ptal

**Pull request merged**
