### PR TITLE
revert cert rotation metrics

### PR DESCRIPTION
**Pull request by deads2k**
they were flaky

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Which PR brought in those changes?  https://github.com/openshift/cluster-kube-scheduler-operator/pull/95?

**Comment by wking** [comment]
[e2e-aws-serial][1]:

```
Failing tests:

[sig-scheduling] SchedulerPredicates [Serial] validates that NodeAffinity is respected if not matching [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates basic preemption works [Suite:openshift/conformance/serial] [Suite:k8s]
[sig-scheduling] SchedulerPreemption [Serial] validates lower priority pod preemption by critical pod [Suite:openshift/conformance/serial] [Suite:k8s]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-kube-scheduler-operator/96/pull-ci-openshift-cluster-kube-scheduler-operator-master-e2e-aws-serial/226

**Pull request merged**
