### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
/assign @ravisantoshgudimetla 

@ravisantoshgudimetla do you have anybody who could be a second approver? Would be good to have one, so we are not blocked when you are out.

**Comment by ravisantoshgudimetla** [comment]
> @ravisantoshgudimetla do you have anybody who could be a second approver? Would be good to have one, so we are not blocked when you are out.

Makes sense @sttts, @sjenning would you like to be 2nd approver? 

@sttts - Since you have been involved in this project right from start, would be interested in becoming another approver?

**Comment by sttts** [comment]
> @sttts - Since you have been involved in this project right from start, would be interested in becoming another approver?

I would be happy to. I would concentrate more on the plumbing, less on deep scheduler config topics.

**Pull request merged**
