### PR TITLE
[release-4.14] OCPBUGS-19553: Update static pod manifests perms

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR bumps library-go to get the latest static pod permissions(more specifically https://github.com/openshift/library-go/pull/1576) and this PR also has to bump kube dependencies to 1.27.4.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/hold
we first need to get these changes into 4.15

**Comment by ardaguclu** [comment]
@knelasevero sorry since I've been managing several PRs, I pinged you in incorrect repo. This is the correct one :)

**Comment by knelasevero** [comment]
> @knelasevero sorry since I've been managing several PRs, I pinged you in incorrect repo. This is the correct one :)

hehe, no worries :)

/approve
/lgtm

**Pull request merged**
