### PR TITLE
move v3.11.0 to v4.1.0

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@ravisantoshgudimetla @sjenning 

This can't merge because I think you hardcoded this into your CI job definition:

```
make: *** No rule to make target `verify-bindata-v3.11.0'.  Stop.
```

We can override this check and land this and you fix your CI afterwards?

**Comment by ravisantoshgudimetla** [comment]
> make: *** No rule to make target `verify-bindata-v3.11.0'.  Stop.

I am  fine with it. But should we have versions in the code? I think, for every release we might have to update it.

**Comment by ravisantoshgudimetla** [comment]
> /override ci/prow/verify

Let me try that.

/override ci/prow/verify

**Comment by ravisantoshgudimetla** [comment]
> @ravisantoshgudimetla: ravisantoshgudimetla unauthorized: /override is restricted to repo administrators

 Ohh no, perhaps @deads2k ?

**Comment by soltysh** [comment]
Done in #170 
/close

**Pull request closed without merging**
