### PR TITLE
bug 2064024: Update library-go to 80f9619c2

### PR DESCRIPTION
**Pull request by pacevedom**
Relates to https://github.com/openshift/library-go/pull/1347, where we increase missing static pods timeout in case we are in single node.

### CODE REVIEW

**Comment by pacevedom** [comment]
@ravisantoshgudimetla @soltysh PTAL

**Comment by ingvagabund** [comment]
@pacevedom do you have a BZ that can be attached to this PR? It's getting required since feature freeze is closed.

**Comment by ingvagabund** [comment]
I see there are other three components pulling this change. Worth reusing the same BZ

**Comment by ingvagabund** [comment]
/retitle bug 2064024: Update library-go to 80f9619c2

**Pull request merged**
