### PR TITLE
Fix verify generated bin data script

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Fix bin generated files, previously we were pointing to v3.10 assets which would have failed.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@ravisantoshgudimetla can you fix the title and description as they are misleading? This PR is fixing the verify script only, not the generated bin data.

**Comment by ravisantoshgudimetla** [comment]
@aveshagarwal Done

**Comment by ravisantoshgudimetla** [comment]
@aveshagarwal anything else needed here? If not can you lgtm?

**Pull request merged**
