### PR TITLE
Bug 2039414: Update KubeSchedulerConfig to v1beta3(default in 1.23)

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Bumping to kubeSchedulerConfig v1beta3 api which is default in kube1.23

cc @damemi @ingvagabund

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/approve

**Comment by ravisantoshgudimetla** [comment]
/hold

Wanted to make sure that the rebase lands first.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ravisantoshgudimetla** [comment]
Localhost failing because of nil pointer dereference. Put a fix in carry patch:

#1121

**Pull request merged**
