### PR TITLE
[release-4.9] Bug 2026109: Disable balancedAllocation and add weight for HighNodeUtilization profile

### PR DESCRIPTION
**Pull request by damemi**
backport of https://github.com/openshift/cluster-kube-scheduler-operator/pull/378

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ingvagabund** [comment]
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
    - [ ] verified
    - [x] does not apply
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
    - [x] verified
    - [ ] does not apply
3. For branches that are in the Maintenance lifecycle phase:
    - [x] The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out, or 
    - [ ] The bug is a security related bug
    - [ ] Branch not in maintenance mode yet (current release + previous release for 90 days after current GA; everything older is in maintenance)
4. The severity field of the bug must be set to accurately reflect criticality.
    - [x] verified
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
    - [x] verified

**Comment by ingvagabund** [comment]
In all the cases up to two (terraform failure, tests going green) the test fails with:
```
=== RUN   TestKSTalksOverPreferredToKas
Found configuration for host https://api.ci-op-yy5nb2sr-58289.origin-ci-int-aws.dev.rhcloud.com:6443.
    ks_preferred_host_kas_test.go:66: getting the current Kube API host
    ks_preferred_host_kas_test.go:69: setting the "unsupported-kube-api-over-localhost" flag and pointing the current master to "https://api-int.ci-op-yy5nb2sr-58289.origin-ci-int-aws.dev.rhcloud.com:1234" (non available host)
    pod_same_revision.go:28: timed out waiting for the condition
--- FAIL: TestKSTalksOverPreferredToKas (510.14s)
```

Not sure what changed since Nov when the test (with the same commit passed). However, the changes are performed under the HighNodeUtilization profile, which is not enabled by default.

/override ci/prow/e2e-aws-operator-preferred-host

**Pull request merged**
