### PR TITLE
[release-4.12] OCPBUGS-19837: Update staticpod file permissions to conform with CIS benchmarks

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR is a manual cherry-pick of these 3 PRs;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

### CODE REVIEW

**Comment by ardaguclu** [comment]
@knelasevero could you PTAL?. Thanks.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
