### PR TITLE
Bug 1758957: hide secrets in logs

### PR DESCRIPTION
**Pull request by soltysh**
/assign @damemi

### CODE REVIEW

**Comment by damemi** [comment]
Do you have a link to the PR that made this change? The bump looks good to me but it might be good to have a link to the library-go change here just for reference

**Comment by soltysh** [comment]
> Do you have a link to the PR that made this change? The bump looks good to me but it might be good to have a link to the library-go change here just for reference

https://github.com/openshift/library-go/pull/557 is the PR for library-go

**Comment by damemi** [comment]
@soltysh thanks, that also helps me know what the bump here is for :p 
/lgtm

**Comment by ashcrow** [comment]
Verifying this is a backport

**Comment by mfojtik** [comment]
This is fixing a CVE

**Pull request merged**
