### PR TITLE
Add a RHEL7 dockerfile and standarize format

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by smarterclayton** [comment]
The job was a test job that isn't checked in, so it can't be retested.  It is failing due to something fixed in a different PR, and will eventually be cleaned up

**Comment by aveshagarwal** [comment]
@smarterclayton not sure how to undo the failing job? also i do not have manual merge rights.

**Comment by sjenning** [comment]
test doesn't show as `Required`.  i think it can still merge.
/lgtm

**Comment by sjenning** [comment]
oh... it was already approved.  weird.  not sure.

**Comment by smarterclayton** [comment]
Hammer

**Pull request merged**
