### PR TITLE
Bug 1705645: Allow configmap resourcelock creation in openshift-kube-scheduler namespace

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Allow configmap resourcelock creation in openshift-kube-scheduler namespace. This should give enough privileges for `kube-scheduler`user to create the needed configmap based mechanism.

/cc @sjenning 

We might remove the bootkube related ones, if this passes.

### CODE REVIEW

**Comment by sjenning** [comment]
confirmed
```
I0506 19:42:49.153618       1 leaderelection.go:205] attempting to acquire leader lease  openshift-kube-scheduler/kube-scheduler...
I0506 19:44:22.077531       1 leaderelection.go:214] successfully acquired lease openshift-kube-scheduler/kube-scheduler
```

**Comment by ravisantoshgudimetla** [comment]
Configmap being created in `openshift-kube-scheduler` ns for leader election.

```
{
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {
                "annotations": {
                    "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"ip-10-0-141-204_51caf6d3-7011-11e9-b129-12f0a4652a1c\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2019-05-06T15:12:29Z\",\"renewTime\":\"2019-05-06T15:47:11Z\",\"leaderTransitions\":1}"
                },
                "creationTimestamp": "2019-05-06T15:06:10Z",
                "name": " *kube-scheduler* ",
                "namespace": "openshift-kube-scheduler",
                "resourceVersion": "116358",
                "selfLink": "/api/v1/namespaces/openshift-kube-scheduler/configmaps/kube-scheduler",
                "uid": "7b7d8605-7010-11e9-8c6b-12f0a4652a1c"
            }
        },

```

**Comment by ravisantoshgudimetla** [comment]
infra flake again.. :(.

/retest

**Comment by ravisantoshgudimetla** [comment]
`May 07 03:25:09.138 W ns/openshift-machine-config-operator pod/etcd-quorum-guard-68b756bbd5-qrsgh 0/6 nodes are available: 2 node(s) didn't match node selector, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) were unschedulable. (118 times)
May 07 03:27:49.852 I test="[Disruptive] Cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade] [Suite:openshift] [Serial]" failed
`

/cc @RobertKrawitz

**Comment by ravisantoshgudimetla** [comment]
` Cluster operator authentication is still updating: upgrading oauth-openshift from 0.0.1-2019-05-07-122655_openshift to 0.0.1-2019-05-07-122933_openshift\n* Cluster operator image-registry is still updating\n* Cluster operator monitoring is still updating\n* Cluster operator openshift-controller-manager is still updating\n* Cluster operator service-ca is still updating\n* Could not update deployment "openshift-console/downloads" (236 of 350)\n* Could not update deployment "openshift-ingress-operator/ingress-operator" (143 of 350)\n* Could not update deployment "openshift-operator-lifecycle-manager/catalog-operator`

**Comment by eparis** [comment]
`rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped`
/retest

**Comment by eparis** [comment]
/retest
twice in a row a cluster didn't even come up. maybe this pr is actually busted?

**Comment by ravisantoshgudimetla** [comment]
>  twice in a row a cluster didn't even come up. maybe this pr is actually busted?

Looks like it is. We don't have enough logs to debug.

**Comment by sjenning** [comment]
I don't know enough about the upgrade test to know, but I'm not sure if the can pass the upgrade test.

```
May 07 23:55:18.967 E ns/openshift-kube-scheduler pod/openshift-kube-scheduler-ip-10-0-175-4.ec2.internal node/ip-10-0-175-4.ec2.internal container=scheduler container exited with code 255 (Error): den: User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope

E0507 23:51:03.106345       1 reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E0507 23:51:03.115784       1 reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E0507 23:51:03.198983       1 leaderelection.go:270] error retrieving resource lock kube-system/kube-scheduler: endpoints "kube-scheduler" is forbidden: User "system:kube-scheduler" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
E0507 23:51:05.198515       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'ip-10-0-175-4_8827212f-711f-11e9-886d-0e2bdfab5888 stopped leading'
I0507 23:51:05.209428       1 leaderelection.go:249] failed to renew lease kube-system/kube-scheduler: failed to tryAcquireOrRenew context deadline exceeded
E0507 23:51:05.209452       1 server.go:259] lost master
I0507 23:51:27.981349       1 secure_serving.go:180] Stopped listening on [::]:10251
```
Some part of the test is still using endpoint leader locks

**Comment by sjenning** [comment]
We are getting the `because it changed` event here
https://github.com/openshift/cluster-kube-scheduler-operator/blob/7f0e5b4c732d25f717ee15ea80501bed0f120d89/vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go#L82

One theory (the only one I have atm) is two kube-schedulers battling over syncing the `system:openshift:sa-listing-configmaps` role

**Comment by ravisantoshgudimetla** [comment]
> We are getting the because it changed event here

Is this in `e2e-aws` log or upgrade log?

**Comment by ravisantoshgudimetla** [comment]
> Unfortunately, there is not enough data captures from the test run to know for certain. Going to try to recreate locally.

Ya, I have set up a cluster, will test the upgrade locally.

**Comment by sjenning** [comment]
> Is this in e2e-aws log or upgrade log?

`build-log.txt` in the upgrade test

**Comment by ravisantoshgudimetla** [comment]
> build-log.txt in the upgrade test

They weren't showing up till the previous run, good that they're back :).

**Comment by sjenning** [comment]
/lgtm
in case it works

**Pull request merged**
