### PR TITLE
Bug 1953563: Enable golang version verify target

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by ingvagabund** [comment]
/hold
until verify-deps tests are fixed.

**Comment by ingvagabund** [comment]
Running `go mod vendor` will do the trick

**Pull request merged**
