### PR TITLE
[hold] Test bump to upstream rc1 prebase branches

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Comment by damemi** [comment]
oh didn't know we were merging this one, weird that "[hold]" in the title didn't add the hold label...

**Comment by deads2k** [comment]
only [wip] works

nice job guys....

**Comment by damemi** [comment]
> only [wip] works
> 
> nice job guys....

Is that intentional/recent? I've definitely held PRs with [hold] before, it's a different label than wip too

**Comment by soltysh** [comment]
> Is that intentional/recent? I've definitely held PRs with [hold] before, it's a different label than wip too

hold only works with `/` which you explicitly invoke, wip worked always

**Pull request merged**
