### PR TITLE
Bug 1810181: Remove wildcard COPY form Dockerfile

### PR DESCRIPTION
**Pull request by tnozicka**
It doesn't work with docker and buildah, only image builder.

/cc @soltysh @bparees

### CODE REVIEW

**Comment by tnozicka** [comment]
image push failure
/retest

**Comment by tnozicka** [comment]
/hold
for manual verification on both clusters

**Comment by tnozicka** [comment]
```podman run -it --rm registry.svc.ci.openshift.org/ocp/4.5:cluster-kube-scheduler-operator /bin/bash -c 'find /usr/share/bootkube/manifests/ -print0 | sort -z | tar -cf - --no-recursion --null -T - --mtime="UTC 1970-01-01" | sha512sum'
tar: Removing leading `/' from member names
df6cf0a3aeae96fea476d6638896097938c0199d79d7b74254f31da6953190d106522510c2563c6ab20b27c0de72f4dfef74e0ddfa3c8b4dc66b355385d2711f  -

**Comment by tnozicka** [comment]
/hold cancel
verified for no changes in https://github.com/openshift/cluster-kube-scheduler-operator/pull/214#issuecomment-595672618

**Comment by damemi** [comment]
Thanks for fixing this @tnozicka!

**Pull request merged**
