### PR TITLE
switch to API in operator.openshift.io

### PR DESCRIPTION
**Pull request by deads2k**
switch to kubeschedulers.operator.openshift.io like the rest of the control plane

@ravisantoshgudimetla

### CODE REVIEW

**Comment by sjenning** [comment]
waiting for test results but LGTM

**Comment by sjenning** [comment]
/lgtm
tests are flaking (terraform failure, router metrics flake)

**Comment by deads2k** [comment]
e2e-aws is a known flake. The others failed on CI infrastructure

**Pull request merged**
