### PR TITLE
Bug 1920619: bump(*): remove default scheduler profile

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @ingvagabund

**Comment by ingvagabund** [comment]
So the relevant change is this:
```
-	// +kubebuilder:default=LowNodeUtilization
-	Profile SchedulerProfile `json:"profile"`
+	Profile SchedulerProfile `json:"profile,omitempty"`
```
right (and all the bits changed by regen)?

**Comment by ingvagabund** [comment]
/hold
valid failure:
```
--- FAIL: TestCheckForFeatureGates (0.00s)
    --- FAIL: TestCheckForFeatureGates/default (0.00s)
        targetconfigcontroller_test.go:77: Expected map[APIPriorityAndFairness:true LegacyNodeRoleBehavior:false NodeDisruptionExclusion:true RotateKubeletServerCertificate:true SCTPSupport:true ServiceNodeExclusion:true SupportPodPidsLimit:true] feature gates to be present but found map[APIPriorityAndFairness:true LegacyNodeRoleBehavior:false NodeDisruptionExclusion:true RemoveSelfLink:false RotateKubeletServerCertificate:true SCTPSupport:true ServiceNodeExclusion:true SupportPodPidsLimit:true]
    --- FAIL: TestCheckForFeatureGates/techpreview (0.00s)
        targetconfigcontroller_test.go:77: Expected map[APIPriorityAndFairness:true LegacyNodeRoleBehavior:false NodeDisruptionExclusion:true RotateKubeletServerCertificate:true SCTPSupport:true ServiceNodeExclusion:true SupportPodPidsLimit:true] feature gates to be present but found map[APIPriorityAndFairness:true LegacyNodeRoleBehavior:false NodeDisruptionExclusion:true RemoveSelfLink:false RotateKubeletServerCertificate:true SCTPSupport:true ServiceNodeExclusion:true SupportPodPidsLimit:true]
```

**Comment by damemi** [comment]
@ingvagabund thanks for noticing that, updated the featuregate test which should pass now 🤞 
/hold cancel

**Pull request merged**
