### PR TITLE
Bug 1812126: increase memory and resource limits for installer and pruner pods

### PR DESCRIPTION
**Pull request by vareti**
This PR picks up the memory resource and limits changes in https://github.com/openshift/library-go/pull/805

### CODE REVIEW

**Comment by vareti** [comment]
/hold

looks like the test failure is not a flake

**Comment by damemi** [comment]
/retest
I saw this e2e-aws-operator prometheus timeout (https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-kube-scheduler-operator/249/pull-ci-openshift-cluster-kube-scheduler-operator-master-e2e-aws-operator/713) on other PRs too

**Comment by vareti** [comment]
@damemi thanks for looking into this. I was not aware that this is a known flake. Let's see if it gets through this time.

**Comment by vareti** [comment]
/hold cancel

test passed and removing the hold label

**Pull request merged**
