### PR TITLE
Bug 2003540: bump library-go 

### PR DESCRIPTION
**Pull request by aojea**
Signed-off-by: Antonio Ojea <aojea@redhat.com>

### CODE REVIEW

**Comment by ingvagabund** [comment]
@aojea do you plan to carry the same change to the master branch as well? Or, is the change already in the master?

**Review by damemi — COMMENTED** [review]
@aojea the bug needs to change its target version to 4.9.0:
> expected the bug to target the "4.9.0" release, but it targets "4.9.z" instead

**Comment by aojea** [comment]
> @aojea the bug needs to change its target version to 4.9.0:
> 
> > expected the bug to target the "4.9.0" release, but it targets "4.9.z" instead

yeah, I'm confused with the process, since 4.9.0 seems to be open only for blocker+ bugs , anyway, will switch to 4.9.0 to see if is accepted too

**Pull request merged**
