### PR TITLE
update cert injection annotations to beta

### PR DESCRIPTION
**Pull request by atiratree**
service-ca-operator uses newer annotations @soltysh

### CODE REVIEW

**Comment by ingvagabund** [comment]
> service-ca-operator uses newer annotations

@atiratree would you mind linking a PR in the service-ca-operator repo or a documentation which describes this change?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/retest

**Comment by atiratree** [comment]
@ingvagabund I could not find this the exact release note for this annotation, but for the ca-bundle annotation it is here: https://docs.openshift.com/container-platform/4.1/release_notes/ocp-4-1-release-notes.html#ocp-4-1-notable-technical-changes 

the `serving-cert-secret-name` can be earliest found in 4.1 docs (also 4.9) here: https://docs.openshift.com/container-platform/4.1/authentication/certificates/service-serving-certificate.html

this is the change that added it: https://github.com/openshift/service-ca-operator/commit/9820fea69bd7c38dc24861bd7b1354e341dc4088#diff-81a43fd4d98d3cb6bac44c7a083efc4f5ad81887646dce6ea0c744dc786369b7

**Comment by ingvagabund** [comment]
Appreciated!!!

**Pull request merged**
