### PR TITLE
[release-4.6] Bug 1891742: bump(library-go): controller/staticpod: reduce noise of …

### PR DESCRIPTION
**Pull request by soltysh**
…not-ready containers

/assign @ingvagabund

### CODE REVIEW

**Comment by ashcrow** [comment]
I can't seem to find the PR that when into the main branch. Is this a 4.6 update only?

**Comment by damemi** [comment]
@ashcrow this looks like it's pulling in changes from https://github.com/openshift/library-go/pull/930, which was originally bumped in master with https://github.com/openshift/cluster-kube-scheduler-operator/pull/294.

@soltysh is that correct? Just trying to leave a trail of the updates here for future reference

**Pull request merged**
