### PR TITLE
[release-4.13] OCPBUGS-19825: Update staticpod file permissions to conform with CIS benchmarks

### PR DESCRIPTION
**Pull request by ardaguclu**
This PR bumps library-go to fetch the changes come with;
* https://github.com/openshift/library-go/pull/1570
* https://github.com/openshift/library-go/pull/1536
* https://github.com/openshift/library-go/pull/1546

### CODE REVIEW

**Comment by ardaguclu** [comment]
@knelasevero could you PTAL (and if you have powers adding backport-risk-assessed)?. Thanks.

**Comment by knelasevero** [comment]
/approve
/lgtm
I dont think I have the powers, but let me try
/label backport-risk-assessed

**Review by soltysh — APPROVED** [review]
/label backport-risk-assessed

**Pull request merged**
