### PR TITLE
[release-4.1] Bug 1810186: Remove wildcard COPY form Dockerfile

### PR DESCRIPTION
**Pull request by tnozicka**
backport of https://github.com/openshift/cluster-kube-scheduler-operator/pull/214

/cc @soltysh @bparees

### CODE REVIEW

**Comment by bparees** [comment]
i'm surprised to see the file deletion, was it dead/obsolete?

**Comment by tnozicka** [comment]
@bparees that was never used or hooked into CI, and there was no OKD so there is no point in pretending we have non rhel dockerfiles. We have removed it later on but never backported it.

**Comment by bparees** [comment]
thanks.

overriding cherry pick and BZ requirement.  lgtm+approval can come from your team

And thanks for jumping on all these.

**Pull request merged**
