### PR TITLE
kube-scheduler: config authnz settings

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @sttts

### CODE REVIEW

**Comment by sttts** [comment]
/approve
lgtm

Giving @ravisantoshgudimetla a chance to look at it.

**Comment by s-urbaniak** [comment]
similar as https://github.com/openshift/cluster-kube-controller-manager-operator/pull/213, 
this, and the controller-manager is currently blocking e2e tests in cluster monitoring (and probably anything that wants to connect to the secure port of controller-manager

**Pull request merged**
