### PR TITLE
Bug 1874056: bump(k8s.io): to 1.19.0

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Comment by damemi** [comment]
/bugzilla refresh
/hold
(hold so this PR doesn't auto merge and switch the BZ to modified before we get the others in)

**Comment by soltysh** [comment]
> /hold
> (hold so this PR doesn't auto merge and switch the BZ to modified before we get the others in)

Don't worry about that, you can always move the BZ back to POST :wink: 
/hold cancel

**Pull request merged**
