### PR TITLE
Bump to k8s 1.23

### PR DESCRIPTION
**Pull request by damemi**
Depends on these bumps:
https://github.com/openshift/api/pull/1076
https://github.com/openshift/apiserver-library-go/pull/76
https://github.com/openshift/client-go/pull/203
https://github.com/openshift/library-go/pull/1259

### CODE REVIEW

**Comment by damemi** [comment]
Failing with this error:
```
          Error: unknown shorthand flag: 'v' in -v=2
          Usage:
            cluster-kube-scheduler-operator operator [flags]

          Flags:
                --config string                    Location of the master configuration file to run from.
            -h, --help                             help for operator
                --kubeconfig string                Location of the master configuration file to run from.
                --listen string                    The ip:port to serve on.
                --namespace string                 Namespace where the controller is running. Auto-detected if run in cluster.
                --terminate-on-files stringArray   A list of files. If one of them changes, the process will terminate.

          unknown shorthand flag: 'v' in -v=2
```
was the [verbosity flag](https://github.com/openshift/cluster-kube-scheduler-operator/blob/master/manifests/0000_25_kube-scheduler-operator_06_deployment.yaml#L34) removed or changed?

**Comment by ingvagabund** [comment]
klog is no longer properly initialized?

**Comment by damemi** [comment]
> klog is no longer properly initialized?

Yeah it's got to be something like that if the flag isn't even showing up in the usage at all

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
