### PR TITLE
Bug 1963730: kube-apiserver failed to load SNI cert and key

### PR DESCRIPTION
**Pull request by p0lyn0mial**
renames `kube-scheduler-certs` to `dynamic` and moves it under the target directory

After this PR:      /etc/kubernetes/static-pod-resources/kube-scheduler-pod-REVISION/dynamic
Previously it was:  /etc/kubernetes/static-pod-resources/kube-scheduler-certs

The target directory holds all files for the current static pod manifest.

As of today, the cert directory is accessed by at least two processes, namely the installer pod and the cert-syncer.
Up until now, there was no coordination between these processes that might have lead to many unexpected errors, like https://bugzilla.redhat.com/show_bug.cgi?id=1963730

Moving the cert directory to the target directory (revisioned) ensures that these processes won't step each other's toes

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
/hold

for the fake bump

**Comment by ingvagabund** [comment]
Not sure I can review anything here wrt. the certs besides "The changes respect the new bump". Other PRs for other operators are alike. Given the library-go PR got properly reviewed and merged, we just need to make sure all the tests go green. @p0lyn0mial anything else you would like to review from us?

**Comment by p0lyn0mial** [comment]
@ingvagabund This PR changes the location of the dynamic certificates. Just wanted to let you know about the change.

After: `/etc/kubernetes/static-pod-resources/kube-scheduler-pod-REVISION/dynamic`
Before: `/etc/kubernetes/static-pod-resources/kube-scheduler-certs`

**Comment by p0lyn0mial** [comment]
/hold

as it is not clear if the DR scripts will work

**Comment by p0lyn0mial** [comment]
/close

closing in favour of https://github.com/openshift/cluster-kube-scheduler-operator/pull/354

**Pull request closed without merging**
