### PR TITLE
update cluster-kube-scheduler-operator

### PR DESCRIPTION
**Pull request by aveshagarwal**
@sjenning @sttts

### CODE REVIEW

**Comment by wjiangjay** [comment]
@aveshagarwal Can we and how to update the policy via operator CRD resources?

**Comment by aveshagarwal** [comment]
> @aveshagarwal Can we and how to update the policy via operator CRD resources?

policy config should be updated via its configmap, and operator should watch on its changes and restart scheduler if there is any change/update to the policy. Does it sound ok to you or do you see any issue with it?

**Comment by aveshagarwal** [comment]
```
template pod "e2e-aws" failed: the pod ci-op-zf8jr4j5/e2e-aws failed after 39m37s (failed containers: setup, test): ContainerFailed one or more containers exited

Container setup exited with code 1, reason Error
---
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating cluster..."
level=info msg="Waiting up to 30m0s for the Kubernetes API..."
level=fatal msg="waiting for Kubernetes API: context deadline exceeded"
```

seems like some infrastructure issue.

**Comment by wjiangjay** [comment]
@aveshagarwal  target configmap is openshift-kube-scheduler/config? do these changes need make openshift-kube-scheduler offline on CVO to make the changes work?

**Pull request closed without merging**
