### PR TITLE
move from componentconfig/v1alpha1 to kubescheduler.config.k8s.io/v1alpha1

### LINKED ISSUE #63: scheduler config file apiVersion is deprecated.
Noticing the following issue:

```
WARNING: the provided config file is an unsupported apiVersion ("componentconfig/v1alpha1"), which will be removed in future releases

WARNING: switch to command-line flags or update your config file apiVersion to "kubescheduler.config.k8s.io/v1alpha1"

WARNING: apiVersions at alpha-level are not guaranteed to be supported in future releases
```

### PR DESCRIPTION
**Pull request by sjenning**
fixes #63 

@ravisantoshgudimetla

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Just verified the CI logs, I don't see the deprecated message.

**Comment by sttts** [comment]
:+1:

**Pull request merged**
