### PR TITLE
Add an e2e test for verifying that cluster-kube-scheduler-operator deployment is up.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@sjenning

### CODE REVIEW

**Comment by aveshagarwal** [comment]
https://github.com/openshift/release/pull/2420 should fix unit test failure here.

**Comment by aveshagarwal** [comment]
@sjenning tests are passing now, please lgtm after review.

**Comment by sjenning** [comment]
output is a little confusing with no tests to run
```
$ make e2e
go test -v ./test/e2e/...
found operator deployment
testing: warning: no tests to run
PASS
ok  	github.com/openshift/cluster-kube-scheduler-operator/test/e2e	(cached) [no tests to run]
```
but it moves us in the right direction
/lgtm
/approve

**Pull request merged**
