### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by soltysh**
It looks like #67 broke deps, which are constantly failing in #80. This does a fresh bump.

### CODE REVIEW

**Comment by soltysh** [comment]
`git add -f .` solved the problem for me, it was missing hidden files /cc @damemi

**Comment by ravisantoshgudimetla** [comment]
ohh @soltysh, thanks for picking this up, I had a PR https://github.com/openshift/cluster-kube-scheduler-operator/pull/83 up yesterday but couldn't complete it before the end of my day but thanks, wondering why you have 194 files while I have 60 files in my bump and yes I did `git add -f` too.

**Comment by soltysh** [comment]
@ravisantoshgudimetla I'm guessing it's the time between when you did the bump and I did, stuff merged in between so it required more changes

**Comment by ravisantoshgudimetla** [comment]
Flake related to https://search.svc.ci.openshift.org/?search=subPath+should+be+able&maxAge=12h&context=0

/retest

**Pull request merged**
