### PR TITLE
Update OWNERS file to add new reviewers/approvers

### PR DESCRIPTION
**Pull request by damemi**
Adds me, Maciej, and Jan to owners as reviewers/approvers

### CODE REVIEW

**Comment by damemi** [comment]
Do we need to remove anyone? Owners list is getting big and I don't know if everyone on it is actively working on this repo

**Comment by sttts** [comment]
/lgtm
/approve
/hold

Unhold any time when the question about who to delete is clarified.

@sjenning @ravisantoshgudimetla  do you want to stay in the list?

**Comment by ravisantoshgudimetla** [comment]
I am fine taking my name off but my original intention was to be on for few more weeks.

**Comment by sttts** [comment]
> I am fine taking my name off but my original intention was to be on for few more weeks.

No hurry, we leave you there then :)

**Comment by soltysh** [comment]
It's not that big, let's keep Ravi around for a few more weeks as mentioned before. When removing Ravi we can also remove Seth, since he's there as a team lead where scheduler used to be. Rest should be there as is.
/hold cancel

**Pull request merged**
